Repository wildcodeschool-2025-03/strasgite, pull requests merged in 2025-04, with the labels that each got.

#2 S01 us01 composant header
  client/src/App.css
  client/src/App.tsx
  client/src/components/NavBar.tsx
  client/src/components/burger.tsx
  client/src/components/header.tsx
Labels: Add feature

#4 S01 us01 composant header
  client/src/App.css
  client/src/App.tsx
  client/src/components/NavBar.tsx
  client/src/main.tsx
Labels: Fix

#5 ajout formulaire HTML + Responsive Tailwind + Typage + Biome vérifié
  client/src/App.css
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/Contact.tsx
Labels: Add feature, invalid

#7 Ajout du composant Formulaire et fix Header
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/Calendrier.tsx
  client/src/components/Formulaire.tsx
  client/src/components/header.tsx
  client/src/pages/Accueil.tsx
  package-lock.json
Labels: Fix, Add feature

#8 S1 us11 us3
  client/src/App.css
  client/src/components/Calendrier.tsx
  client/src/components/Footer.tsx
  client/src/components/Formprovisoire.tsx
  client/src/pages/Reservation.tsx
Labels: Add feature

#9 S1 us12 page service presentation avec composant cartes services
  client/src/components/CartesServices.tsx
  client/src/main.tsx
  client/src/pages/Services.tsx
Labels: Add feature

#11 Carte interactive composant LMap de leafletJs + intégration dans la …
  client/package.json
  client/src/App.css
  client/src/components/Calendrier.tsx
  client/src/components/LMap.tsx
  client/src/pages/Services.tsx
  package-lock.json
Labels: Add feature

#13 Ajout du composant Avis avec début de style sur le calendrier
  client/public/avatar_f_asiatique.png
  client/public/avatar_h_blanc.png
  client/public/avatar_h_noir.png
  client/public/britflag.svg
  client/public/franceflag.svg
  client/public/germanflag.svg
  client/src/App.css
  client/src/components/Avis.tsx
  client/src/components/RatingStars.tsx
  client/src/pages/Accueil.tsx
Labels: Add feature, invalid

#14 S01 us05 pages nos chambres + s01 us18 photos descriptions + s01 us51 ratings component + s01 us50 like component = fix
  client/src/components/NavBar.tsx
  client/src/components/Rooms/RoomShow.tsx
  client/src/main.tsx
  client/src/pages/Accueil.tsx
  client/src/pages/Nos_Chambres.tsx
Labels: Add feature, invalid

#20 S2 us17 photos page services
  client/package.json
  client/public/devanture.png
  client/public/petitdej.png
  client/src/App.css
  client/src/components/LMap.tsx
  client/src/components/SwiperCarousel.tsx
  client/src/pages/Services.tsx
  package-lock.json
Labels: Fix, Add feature

#18 fetch emailJS
  client/package.json
  client/src/pages/Contact.tsx
  client/src/pages/Services.tsx
  package-lock.json
Labels: Fix, Add feature, invalid

#21 S02 us52 composant log in
  client/package.json
  client/public/Untitled.png
  client/public/account.svg
  client/public/devanture.png
  client/public/infobulle.svg
  client/public/petitdej.png
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/Login.tsx
  client/src/components/NavBar.tsx
  client/src/components/Rooms/RoomCard.tsx
  client/src/components/Rooms/RoomList.tsx
  client/src/components/burger.tsx
  client/src/components/context/LoginContext.tsx
  client/src/components/context/RoomsContext.tsx
  client/src/components/header.tsx
  client/src/data/roomsData.json
  client/src/main.tsx
  client/src/pages/Connexion.tsx
  client/src/pages/EspaceVisiteur.tsx
  client/src/pages/Services.tsx
  package-lock.json
Labels: Add feature, invalid
