Repository wildcodeschool-2025-03/strasgite, pull requests merged in 2025-05, with the labels that each got.

#24 FilterRooms+ CONTEXTCalendar + ContextForm + RoomContext + RoomList U…
  client/src/App.tsx
  client/src/components/Calendrier.tsx
  client/src/components/Formulaire.tsx
  client/src/components/Rooms/RoomCarousel.tsx
  client/src/components/Rooms/RoomList.tsx
  client/src/components/SearchFilterRooms.tsx
  client/src/context/CalendarContext.tsx
  client/src/context/FormContext.tsx
  client/src/context/RoomsContext.tsx
  client/src/data/roomsData.json
  client/src/pages/Nos_Chambres.tsx
Labels: Fix, enhancement, Add feature

#25 Ajout theme europe + page espace perso + fix navigation connexion esp…
  client/public/europebanner2.png
  client/src/App.css
  client/src/App.tsx
  client/src/components/EspacePerso.tsx
  client/src/components/Footer.tsx
  client/src/components/Formulaire.tsx
  client/src/components/Login.tsx
  client/src/components/NavBar.tsx
  client/src/components/burger.tsx
  client/src/components/header.tsx
  client/src/context/ThemeContext.tsx
  client/src/pages/EspaceVisiteur.tsx
  client/src/pages/Reservation.tsx
  client/src/pages/Services.tsx
  package-lock.json
Labels: Add feature, invalid

#27 S03 us85 translation
  client/public/baby.png
  client/src/App.tsx
  client/src/components/Avis.tsx
  client/src/components/Calendrier.tsx
  client/src/components/CartesServices.tsx
  client/src/components/Footer.tsx
  client/src/components/Formulaire.tsx
  client/src/components/Login.tsx
  client/src/components/NavBar.tsx
  client/src/components/RatingStars.tsx
  client/src/components/Rooms/RoomShow.tsx
  client/src/components/SearchFilterRooms.tsx
  client/src/components/TranslationButtons.tsx
  client/src/context/FormContext.tsx
  client/src/context/RoomsContext.tsx
  client/src/context/TranslationContext.tsx
  client/src/pages/Accueil.tsx
  client/src/pages/Cgv.tsx
  client/src/pages/Contact.tsx
  client/src/pages/EspaceVisiteur.tsx
  client/src/pages/Legal.tsx
  client/src/pages/Nos_Chambres.tsx
  client/src/pages/Notre_Alsace.tsx
  client/src/pages/Order.tsx
  client/src/pages/Reservation.tsx
  client/src/pages/Services.tsx
  client/src/translations/english.json
  client/src/translations/french.json
  client/src/translations/german.json
  package-lock.json
Labels: Fix, enhancement, Add feature

#28 bug Fix
  client/src/components/Calendrier.tsx
  client/src/context/CalendarContext.tsx
  client/src/context/FormContext.tsx
  client/src/pages/Notre_Alsace.tsx
  client/src/pages/Order.tsx
  client/src/pages/Reservation.tsx
Labels: Fix

#30 Fixcalendar
  client/src/App.css
  client/src/components/Calendrier.tsx
  client/src/context/CalendarContext.tsx
  client/src/context/FormContext.tsx
  client/src/context/LoginContext.tsx
  client/src/pages/EspaceVisiteur.tsx
  client/src/pages/Order.tsx
Labels: Fix

#31 Style updater rooms
  client/src/App.css
  client/src/components/Formulaire.tsx
  client/src/components/NavBar.tsx
  client/src/components/Rooms/RoomCard.tsx
  client/src/components/Rooms/RoomCarousel.tsx
  client/src/components/Rooms/RoomList.tsx
  client/src/components/SearchFilterRooms.tsx
  client/src/components/TranslationButtons.tsx
  client/src/components/header.tsx
  client/src/context/RoomsContext.tsx
  client/src/data/roomsData.json
  client/src/pages/Nos_Chambres.tsx
  client/src/pages/Reservation.tsx
  client/src/pages/Services.tsx
Labels: Fix, Add feature

#33 S04 us99 final count down
  client/index.html
  client/public/calendar.png
  client/public/customer.png
  client/public/sleeping.png
  client/src/App.css
  client/src/assets/images/background.webp
  client/src/components/Calendrier.tsx
  client/src/components/EspacePerso.tsx
  client/src/components/Formulaire.tsx
  client/src/components/Login.tsx
  client/src/components/NavBar.tsx
  client/src/components/Rooms/RoomCard.tsx
  client/src/components/Rooms/RoomCarousel.tsx
  client/src/components/Rooms/RoomShow.tsx
  client/src/components/SearchFilterRooms.tsx
  client/src/components/header.tsx
  client/src/context/LoginContext.tsx
  client/src/pages/Cgv.tsx
  client/src/pages/Contact.tsx
  client/src/pages/EspaceVisiteur.tsx
  client/src/pages/Legal.tsx
  client/src/pages/Notre_Alsace.tsx
  client/src/pages/Order.tsx
  client/src/pages/Reservation.tsx
  client/src/translations/english.json
  client/src/translations/french.json
  client/src/translations/german.json
Labels: Fix, enhancement, Add feature

#35 push finale fix léger avant presentation
  client/src/components/Formulaire.tsx
  client/src/pages/Notre_Alsace.tsx
  client/src/pages/Order.tsx
  client/src/translations/english.json
  client/src/translations/french.json
  client/src/translations/german.json
Labels: Fix
